const englishCopy = {
  '主页': 'Home',
  '控制台': 'Dashboard',
  '模型广场': 'Models',
  '在线生图': 'Image generation',
  '文档': 'Docs',
  '更改语言': 'Change language',
  '语言': 'Language',
  '切换浅色主题': 'Switch to light theme',
  '切换深色主题': 'Switch to dark theme',
  '切换主题': 'Toggle theme',
  '登录后查看公告': 'Sign in to view announcements',
  '登录': 'Sign in',
  '切换导航菜单': 'Toggle navigation menu',
  '网站导航': 'Site navigation',
  '统一 API 网关，服务于': 'One API gateway for',
  '海量 AI 模型': 'a world of AI models',
  '通过统一、标准的接口协议接入海量模型。承载 AI 应用，高效管理数字资产，连接未来。': 'Access AI models through a single, standard interface. Power your applications, manage digital resources, and connect to what comes next.',
  '开始使用': 'Get started',
  '查看定价': 'View pricing',
  '常用应用支持': 'Your favorite apps, connected',
  '通过{siteName} 接入常用 AI 应用与开发工具': 'Connect your AI apps and development tools through {siteName}',
  'WorkBuddy 配置指南': 'WorkBuddy setup guide',
  '更多': 'More',
  '接口调用示例（静态演示）': 'API request example (static demonstration)',
  'API 协议': 'API protocols',
  '多厂商': 'Providers',
  '模型统一接入': 'One interface for every model',
  '按量': 'Usage',
  '用量与费用记录': 'Usage and cost records',
  '多协议': 'Protocols',
  '兼容 API 调用': 'Compatible API requests',
  '分组': 'Groups',
  '权限与调度管理': 'Access and scheduling',
  '核心功能': 'Core features',
  '为开发者打造，': 'Built for developers,',
  '为规模而设计': 'designed to scale',
  '极速': 'Fast integration',
  '统一接入多家模型，减少应用适配工作': 'Connect models from multiple providers with less integration work',
  '安全可靠': 'Secure access',
  'API 密钥与权限分组，管理用户访问': 'Manage user access with API keys and permission groups',
  '稳定调度': 'Reliable scheduling',
  '分组与限流，统一管理上游请求': 'Manage upstream requests with groups and rate limits',
  '负载均衡': 'Load balancing',
  '速率限制': 'Rate limits',
  '成本跟踪': 'Cost tracking',
  '开发者友好': 'Developer friendly',
  '兼容常见 AI 应用工作流的 API 路由': 'API routes that fit common AI app workflows',
  '兼容多协议': 'Multiple protocols',
  '高性能': 'Performance',
  '支持并发控制和账号调度': 'Concurrency controls and account scheduling',
  '透明计费': 'Transparent billing',
  '按量付费，实时监控使用情况': 'Pay for usage and track it in real time',
  '团队协作': 'Team access',
  '用户与分组管理，灵活分配权限': 'Manage users and groups with flexible permissions',
  '灵活扩展': 'Flexible integration',
  '{siteName}支持多种 API 协议与应用接入': '{siteName} supports multiple API protocols and app integrations',
  '工作流程': 'How it works',
  '三步快速上手': 'Get started in three steps',
  '配置': 'Configure',
  '注册账号，创建你的 API 密钥并选择可用模型': 'Create an account, generate an API key, and choose an available model',
  '连接': 'Connect',
  '通过 OpenAI、Claude、Gemini 以及其他兼容 API 路由接入': 'Connect through OpenAI, Claude, Gemini, and other compatible API routes',
  '监控': 'Monitor',
  '通过实时分析跟踪用量、成本和性能': 'Track usage, cost, and performance with real-time analytics',
  '准备好简化': 'Ready to simplify',
  '你的 AI 集成了吗？': 'your AI integration?',
  '在{siteName} 创建 API 密钥，将本站模型接入你的应用与开发工具。': 'Create an API key on {siteName} and connect our models to your apps and development tools.',
  '强大的 API 管理平台': 'A powerful API management platform',
  '版权所有。': 'All rights reserved.',
  '由{siteName}提供服务': 'Service provided by {siteName}',
} as const

export type LandingCopyKey = keyof typeof englishCopy

export function translateLandingCopy(key: LandingCopyKey, locale: 'zh' | 'en', siteName: string): string {
  return (locale === 'en' ? englishCopy[key] : key).split('{siteName}').join(siteName)
}
